# Generated by Django 4.2.3 on 2023-07-28 06:59

from django.db import migrations, models
import django.db.models.deletion
import tracks.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("albums", "0001_initial"),
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="tracks/",
                        validators=[tracks.validators.validate_is_audio],
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="artists.artist",
                    ),
                ),
            ],
        ),
    ]
