# Generated by Django 4.2.3 on 2023-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="path",
        ),
        migrations.AddField(
            model_name="track",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="static/tracks/"),
        ),
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
