# Generated by Django 4.2.3 on 2023-07-21 03:51

from django.db import migrations, models
import django.db.models.deletion
import tracks.validators


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
        ("tracks", "0002_remove_track_path_track_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="artists.artist",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.FileField(
                default=1,
                upload_to="static/tracks/",
                validators=[tracks.validators.validate_is_audio],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
