# Generated by Django 4.2.3 on 2023-07-24 14:09

from django.db import migrations, models
import django.db.models.deletion
import tracks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0003_track_artist_alter_track_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/', validators=[tracks.validators.validate_is_audio]),
        ),
    ]
