name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: dias
          POSTGRES_PASSWORD: 0706
          POSTGRES_DB: harmonyflow
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Django Database
      run: |
        python manage.py makemigrations
        python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: harmonyflow.settings
        DB_HOST: localhost
        DB_NAME: harmonyflow
        DB_USER: dias
        DB_PASS: 0706
        DB_PORT: 5432

    - name: Run Tests
      run: python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: harmonyflow.settings
        DB_HOST: localhost
        DB_NAME: harmonyflow
        DB_USER: dias
        DB_PASS: 0706
        DB_PORT: 5432
